# Micronaut Application
micronaut.application.name=microservice-reservations
micronaut.server.context-path=${BASE_PATH:/}

# CORS
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.ui.allowed-origins[0]="*"
micronaut.server.cors.configurations.ui.allowed-methods[0]=GET
micronaut.server.cors.configurations.ui.allowed-methods[1]=PUT
micronaut.server.cors.configurations.ui.allowed-methods[2]=POST
micronaut.server.cors.configurations.ui.allowed-methods[3]=DELETE
micronaut.server.cors.configurations.ui.allowed-methods[4]=OPTIONS

# Hibernate
jpa.default.properties.hibernate.hbm2ddl.auto=none

# Liquibase
liquibase.datasources.default.change-log=classpath\:db/main.xml

# PostgreSQL
datasources.default.url=${DATASOURCES_DEFAULT_URL}
datasources.default.username=${DATASOURCES_DEFAULT_USERNAME}
datasources.default.password=${DATASOURCES_DEFAULT_PASSWORD}
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver

# Billing microservice
service.billing.url=${BILLING_SERVICE_URL}

# Otel whooo
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none

# Configure endpoint for Traces
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
otel.exporter.otlp.protocol=grpc
otel.service.name=${micronaut.application.name}

# Configure endpoint for Metrics
micronaut.metrics.enabled=true
micronaut.metrics.export.otlp.enabled=true
micronaut.metrics.export.otlp.step=PT15S
micronaut.metrics.export.otlp.url=${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}

# Exclude health check endpoints
otel.exclusions[0]=.*/health/live
otel.exclusions[1]=.*/health/ready
otel.exclusions[2]=.*/metrics.*
otel.exclusions[3]=.*/health/?.*
