apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-lobby.fullname" . }}-config
data:
  CLEANING_SERVICE_URL: "http://{{ .Values.cleaning.service.name }}.{{ .Values.cleaning.service.namespace }}.svc.cluster.local{{ .Values.cleaning.service.basePath }}"
  RESERVATIONS_SERVICE_URL: "http://{{ .Values.reservations.service.name }}.{{ .Values.reservations.service.namespace }}.svc.cluster.local{{ .Values.reservations.service.basePath }}"
  BILLING_SERVICE_URL: "http://{{ .Values.billing.service.name }}.{{ .Values.billing.service.namespace }}.svc.cluster.local{{ .Values.billing.service.basePath }}"
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.opentelemetry.exporterEndpoint | quote }}
  BASE_PATH: {{ .Values.basePath | quote }}
